const START_MINIMIZED_ARG = '--start-minimised';
const UPDATE_CHECK_INTERVAL_MS = 24 * 60 * 60 * 1000;
const BOUNDS_SAVE_DEBOUNCE_MS = 150;
const DEFAULT_OPACITY = 0.94;
const MIN_OPACITY = 0.35;

module.exports = {
  START_MINIMIZED_ARG,
  UPDATE_CHECK_INTERVAL_MS,
  BOUNDS_SAVE_DEBOUNCE_MS,
  DEFAULT_OPACITY,
  MIN_OPACITY
};
